
[platformio]
default_envs = jumper_zero_RP2040

; ////////////////////RP2040 Jumper Zero Board////////////////////

[env:jumper_zero_RP2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board = jumper_z_rp2040
framework = arduino
upload_port = F:
; extra_scripts = pre:scripts/find_JumperZ_upload.py, post:scripts/extra_script.py
extra_scripts = pre:scripts/apply_patches.py , post:scripts/extra_script.py
board_build.variants_dir = Variants
board_build.variant = RP2040_VARIANT
monitor_speed = 115200


build_src_filter =
  +<rp2040/*>
  -<esp32s3/*>
 


build_flags = 
  -DUSE_TINYUSB
	-DCFG_TUSB_CONFIG_FILE=\"custom_tusb_config.h\"
  -DCFG_TUD_DESC_AUTO=1
  ; -Wl,--wrap=tud_cdc_line_state_cb



  -Iinclude/
  -I src/rp2040/pin_map
  -I src/rp2040/RGB_MATRIX
  -I src/rp2040/SERIAL_STUFF
  -I src/rp2040/UART_BRIDGE
  -I src/rp2040/JSON_HANDLER
  -I src/rp2040/MEASUREMENTS
  -I src/rp2040/PATH_FINDING
  -I src/rp2040/CH446Q_HANDLER
  -I src/rp2040/SEQUENCE_HANDLER
  -I src/rp2040/NANO_HEADER
  -I src/rp2040/SPI_HANDLER
  -I src/rp2040/DEBUG
  -I src/rp2040/RGB_MATRIX/LED_PATTERNS


lib_ignore = SoftwareSPI

lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.0
  adafruit/Adafruit TinyUSB Library
  https://github.com/bblanchon/ArduinoJson.git
  


; ////////////////////ESP32S3 Jumper Zero Board////////////////////

[env:jumper_zero_ESP32S3]
platform = espressif32
board = jumper_z_esp32s3
framework = arduino
monitor_speed = 115200

board_build.variants_dir = Variants
board_build.variant = ESP32S3_VARIANT

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

    -Iinclude/
    -I src/esp32s3/pin_map
    -I src/esp32s3/UART_BRIDGE


build_src_filter =
  -<rp2040/*>
  +<esp32s3/*>



