

; ////////////////////RP2040 Jumper Zero Board////////////////////

[env:jumper_zero_RP2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board = jumper_z_rp2040
framework = arduino
upload_port = F:
extra_scripts = pre:scripts/find_JumperZ_upload.py, post:scripts/extra_script.py
board_build.variants_dir = Variants
board_build.variant = RP2040_VARIANT



build_src_filter =
  +<rp2040/*>
  -<esp32s3/*>
 


build_flags = 
  -DUSE_TINYUSB
	-DCFG_TUSB_CONFIG_FILE=\"custom_tusb_config.h\"
  -DCFG_TUD_DESC_AUTO=0


  -Iinclude/
  -I src/rp2040/pin_map
  -I src/rp2040/RGB_MATRIX
  -I src/rp2040/SERIAL_STUFF
  -I src/rp2040/UART_BRIDGE
  -I src/rp2040/JSON_HANDLER
  -I src/rp2040/MEASUREMENTS


lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.0
  adafruit/Adafruit TinyUSB Library
  https://github.com/bblanchon/ArduinoJson.git
  


; ////////////////////ESP32S3 Jumper Zero Board////////////////////

[env:jumper_zero_ESP32S3]
platform = espressif32
board = jumper_z_esp32s3
framework = arduino
monitor_speed = 115200

board_build.variants_dir = Variants
board_build.variant = ESP32S3_VARIANT

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

build_src_filter =
  -<rp2040/*>
  +<esp32s3/*>