"""
scripts/generate_tree.py

Scans the project directory and writes a clean tree to docs/tree.md.
Designed for the JUMPER-Z desktop application project.

Usage:
    python scripts/generate_tree.py              # auto-detects project root
    python scripts/generate_tree.py --root .     # explicit root
    python scripts/generate_tree.py --dry-run    # print to stdout, don't write

Integrate into dev workflow:
    - Call from bootstrap.py in dev mode (IS_BUNDLE=False)
    - Or wire as a pre-commit hook (see bottom of file)
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import Iterator

# ================================================================
#  Configuration
# ================================================================

# Directories excluded entirely (not shown at all)
EXCLUDED_DIRS: frozenset[str] = frozenset({
    "__pycache__",
    ".git",
    ".idea",
    ".vscode",
    "node_modules",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "dist",
    "build",
    "*.egg-info",
})

# Files excluded by exact name
EXCLUDED_FILES: frozenset[str] = frozenset({
    ".DS_Store",
    "Thumbs.db",
    ".gitkeep",
})

# Files excluded by suffix
EXCLUDED_SUFFIXES: frozenset[str] = frozenset({
    ".pyc",
    ".pyo",
    ".log",
    ".tmp",
    ".swp",
})

# Directories shown but NOT expanded (collapsed with a note)
COLLAPSED_DIRS: frozenset[str] = frozenset({
    ".venv",
    "venv",
    "env",
})

# Tree drawing characters (Unicode box-drawing)
PIPE      = "│"
TEE       = "├──"
ELBOW     = "└──"
BLANK     = "    "
PIPE_PAD  = "│   "

# Output path relative to project root
OUTPUT_PATH = Path("docs") / "tree.md"

# Script version — bump when behaviour changes
SCRIPT_VERSION = "1.2.0"


# ================================================================
#  Core tree-building logic
# ================================================================

def _should_exclude_dir(name: str) -> bool:
    """Return True if this directory should be skipped entirely."""
    return name in EXCLUDED_DIRS or name.endswith(".egg-info")


def _should_exclude_file(name: str) -> bool:
    """Return True if this file should be skipped."""
    return (
        name in EXCLUDED_FILES
        or Path(name).suffix in EXCLUDED_SUFFIXES
    )


def _should_collapse_dir(name: str) -> bool:
    """Return True if this directory should appear but not be expanded."""
    return name in COLLAPSED_DIRS


def _iter_entries(
    directory: Path,
) -> Iterator[tuple[Path, bool]]:
    """
    Yield (path, is_last) pairs for sorted directory contents,
    directories first then files, both alphabetically.
    Excludes filtered entries before yielding.
    """
    try:
        all_entries = list(directory.iterdir())
    except PermissionError:
        return

    dirs  = sorted(
        e for e in all_entries
        if e.is_dir() and not _should_exclude_dir(e.name)
    )
    files = sorted(
        e for e in all_entries
        if e.is_file() and not _should_exclude_file(e.name)
    )

    entries = dirs + files
    for i, entry in enumerate(entries):
        yield entry, (i == len(entries) - 1)


def _build_tree(
    directory: Path,
    prefix: str = "",
    lines: list[str] | None = None,
) -> list[str]:
    """
    Recursively build tree lines for `directory`.
    Returns a list of formatted strings (without newlines).
    """
    if lines is None:
        lines = []

    for entry, is_last in _iter_entries(directory):
        connector = ELBOW if is_last else TEE
        extension = BLANK if is_last else PIPE_PAD

        if entry.is_dir():
            if _should_collapse_dir(entry.name):
                # Show the folder, note it's collapsed, stop recursing
                lines.append(f"{prefix}{connector} {entry.name}/  [not expanded]")
            else:
                lines.append(f"{prefix}{connector} {entry.name}/")
                _build_tree(entry, prefix + extension, lines)
        else:
            lines.append(f"{prefix}{connector} {entry.name}")

    return lines


def generate_tree(root: Path) -> str:
    """
    Build the full tree string rooted at `root`.
    Returns the complete Markdown document as a string.
    """
    now        = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    root_label = root.resolve().name

    tree_lines = _build_tree(root)
    tree_body  = "\n".join(tree_lines)

    # Exclusion summary for the legend
    excluded_note = ", ".join(sorted(EXCLUDED_DIRS - {"*.egg-info"}))
    collapsed_note = ", ".join(sorted(COLLAPSED_DIRS))

    return f"""\
# Project structure

> Auto-generated by `scripts/generate_tree.py` v{SCRIPT_VERSION}
> Last updated: **{now}**

## Directory tree

```
{root_label}/
{tree_body}
```

## Legend

| Symbol | Meaning |
|--------|---------|
| `/` suffix | Directory |
| `[not expanded]` | Directory exists but contents are hidden |

## Exclusions

**Excluded entirely:** `{excluded_note}`

**Collapsed (shown, not expanded):** `{collapsed_note}`

**Excluded file types:** {", ".join(f"`{s}`" for s in sorted(EXCLUDED_SUFFIXES))}
"""


# ================================================================
#  File writing
# ================================================================

def write_tree(root: Path, dry_run: bool = False) -> None:
    """
    Generate the tree and write it to docs/tree.md.
    If dry_run=True, prints to stdout instead.
    """
    content    = generate_tree(root)
    output     = root / OUTPUT_PATH

    if dry_run:
        print(content)
        print(f"\n[dry-run] Would write to: {output}")
        return

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"[generate_tree] Written to {output}")


# ================================================================
#  Bootstrap integration helper
# ================================================================

def update_tree_if_dev(root: Path | None = None) -> None:
    """
    Call this from bootstrap.py in development mode only.

    Example usage in bootstrap.py:
        from src.core.config import IS_BUNDLE, ROOT_DIR
        from scripts.generate_tree import update_tree_if_dev

        if not IS_BUNDLE:
            update_tree_if_dev(ROOT_DIR)
    """
    from pathlib import Path as _Path
    resolved_root = root or _Path(__file__).resolve().parents[1]
    try:
        write_tree(resolved_root)
    except Exception as exc:
        # Never let a documentation tool crash the application
        print(f"[generate_tree] Warning: could not update tree.md — {exc}")


# ================================================================
#  CLI entry point
# ================================================================

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate docs/tree.md for the JUMPER-Z project.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/generate_tree.py
  python scripts/generate_tree.py --root /path/to/project
  python scripts/generate_tree.py --dry-run
        """,
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Project root directory (default: parent of this script)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print output to stdout without writing any files",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    # Auto-detect root: parent directory of scripts/
    root = (args.root or Path(__file__).resolve().parent.parent).resolve()

    if not root.is_dir():
        print(f"[generate_tree] Error: root directory not found: {root}", file=sys.stderr)
        sys.exit(1)

    write_tree(root, dry_run=args.dry_run)


if __name__ == "__main__":
    main()